# Site settings
title: 叶子绿的天空
email: xiongzhijian51@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
   一个靠谱的前端，一个追求梦想的北漂。。。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://heyi.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  heyi

# Build settings
markdown: kramdown

destination: ./_site
lsi:         false
highlighter:   pygments
paginate: 5
paginate_path: "blog/page:num"
permalink:   date
extensions: [smart]
exclude_from_search: true
lunr_search:
  excludes: [rss.xml, atom.xml]

lunr_search:
    stopwords: "stopwords.txt"
    min_length: 3

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
