destination: ./_site
lsi:         false
pygments:    true
paginate: 5
paginate_path: "blog/page:num"
permalink:   date
extensions: [smart]

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "default"
