destination: ./_site
lsi:         false
pygments:    true
permalink:   date
extensions: [smart]
#markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "default"
